### ISSUE TITLE
Error version option 

### ISSUE THREAD

**Issue by cfhamlet** [cfhamlet/os-aio-pod#1]
@inyouth  version option don't work, can you fix it?
```
os-aio-pod --version
Traceback (most recent call last):
  File "/root/.pyenv/versions/os-aio-pod-py36/bin/os-aio-pod", line 11, in <module>
    load_entry_point('os-aio-pod', 'console_scripts', 'os-aio-pod')()
  File "/search/workspace/project/os-aio-pod/src/os_aio_pod/main.py", line 6, in main
    execute(command_packages=command_packages)
  File "/search/workspace/project/os-aio-pod/src/os_aio_pod/cmdline.py", line 38, in execute
    cli()
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/root/.pyenv/versions/3.6.4/envs/os-aio-pod-py36/lib/python3.6/site-packages/click/decorators.py", line 270, in callback
    raise RuntimeError('Could not determine version')
RuntimeError: Could not determine version
```

**Comment by cfhamlet** [comment]
@inyouth thanks #2
